version: '3.5'

services: 
  adore_cli_core:
    privileged: true
    image: ${ADORE_CLI_PROJECT}:${ADORE_CLI_TAG:-latest}
    container_name: ${ADORE_CLI_PROJECT}_base
    user: ${USER}
    hostname: ${HOSTNAME:-ADORe-CLI}
    network_mode: "host"
    ipc: "host"
    pid: "host"
    environment:
      - HOSTNAME=${HOSTNAME:-ADORe-CLI}
      - TEST_SCENARIOS=${TEST_SCENARIOS:-baseline_test.launch}
      - "BAG_OUTPUT_DIRECTORY=${SOURCE_DIRECTORY}/.log/.ros/bag_files"
      - "ROS_HOME=${SOURCE_DIRECTORY}/.log/.ros"
      - "HISTFILE=${SOURCE_DIRECTORY}/.zsh_history"
    # depends_on:
      #- ros-master  #activate this option if you want to start roscore on startup of adore_cli container
    build:
      context: ${ADORE_CLI_MAKEFILE_PATH}
      network: host
      dockerfile: ${ADORE_CLI_MAKEFILE_PATH}/docker/Dockerfile.adore_cli
      args:
        - HOSTNAME=${HOSTNAME:-ADORe-CLI}
        - ADORE_CLI_TAG=${ADORE_CLI_TAG:-latest}
        - USER=${USER}
        - UID=${UID:-1000}
        - GID=${GID:-1001}
    volumes:
      - ./:/tmp/adore
      - /var/run/docker.sock:/var/run/docker.sock
      - ${SOURCE_DIRECTORY}:/tmp/adore
      - ${SOURCE_DIRECTORY}:${SOURCE_DIRECTORY}
      - ${ADORE_CLI_MAKEFILE_PATH}/.ccache:/home/${USER}/.ccache
      - ${SOURCE_DIRECTORY}/.log:/var/log/ros2

  adore_cli_core_x11_display:
    privileged: true
    ipc: "host"
    pid: "host"
    image: ${ADORE_CLI_PROJECT_X11_DISPLAY}:${ADORE_CLI_TAG:-latest}
    container_name: ${ADORE_CLI_PROJECT}
    user: ${USER} 
    hostname: ${HOSTNAME:-ADORe-CLI}
    network_mode: "host"
    environment:
      - HOSTNAME=${HOSTNAME:-ADORe-CLI}
      - ADORE_SOURCE_DIRECTORY=${SOURCE_DIRECTORY}
      - SOURCE_DIRECTORY=${SOURCE_DIRECTORY}
      - ADORE_CLI_WORKING_DIRECTORY=${ADORE_CLI_WORKING_DIRECTORY}
      - DISPLAY_MODE=${DISPLAY_MODE:-native}
      # - DISPLAY_MODE=${DISPLAY_MODE:-window_manager}
      # - DISPLAY_MODE=${DISPLAY_MODE:-headless}
      - DISPLAY=${DISPLAY}
      - USER=${USER}
      - UID=${UID}
      - GID=${GID}
      - TEST_SCENARIOS=${TEST_SCENARIOS:-baseline_test.launch}
      - "BAG_OUTPUT_DIRECTORY=${SOURCE_DIRECTORY}/.log/.ros/bag_files"
      - "ROS_HOME=${SOURCE_DIRECTORY}/.log/.ros"
      - "HISTFILE=${SOURCE_DIRECTORY}/.zsh_history"
      - "ROS_MASTER_URI=http://127.0.0.1:11311"
      - "ROS_HOSTNAME=127.0.0.1"
    # depends_on:
      # - ros-master  #activate this option if you want to start roscore on startup of adore_cli container
    build:
      context: ${ADORE_CLI_MAKEFILE_PATH}
      network: host
      dockerfile: ${ADORE_CLI_MAKEFILE_PATH}/docker/Dockerfile.adore_cli_x11_display
      args:
        - HOSTNAME=${HOSTNAME:-ADORe-CLI}
        - ADORE_CLI_TAG=${ADORE_CLI_TAG:-latest}
        - ADORE_IF_ROS_TAG=${ADORE_IF_ROS_TAG:-latest}
        - USER=${USER}
        - UID=${UID:-1000}
        - GID=${GID:-1001}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/tmp/adore_cli
      - ${SOURCE_DIRECTORY}:/tmp/adore
      - ${SOURCE_DIRECTORY}:${SOURCE_DIRECTORY}
      - ${ADORE_CLI_MAKEFILE_PATH}/.ccache:/home/${USER}/.ccache
      - ${SOURCE_DIRECTORY}/.log:/var/log/ros2
    extra_hosts:
      - "${HOSTNAME:-ADORe-CLI}:127.0.0.1"
