version: '3.3'

services:
  adore_cli:
    extends:
      file: ${ADORE_CLI_MAKEFILE_PATH}/adore_cli.yaml
      service: adore_cli

  adore_cli_x11_display:
    extends:
      file: ${ADORE_CLI_MAKEFILE_PATH}/adore_cli.yaml
      service: adore_cli_x11_display
