ARG ADORE_CLI_TAG=latest

ARG REQUIREMENTS_FILE
ARG USER

FROM adore_cli_core:${ADORE_CLI_TAG} as adore_cli

ARG USER
ARG REQUIREMENTS_FILE="requirements.adore_cli_x11_display.ubuntu20.04.system"

USER root
COPY docker/files/${REQUIREMENTS_FILE} /tmp
WORKDIR /tmp
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install --no-install-recommends -y $(sed '/^#/d' ${REQUIREMENTS_FILE} | sed '/^$/d') && \
    rm -rf /var/lib/apt/lists/*


USER $USER
WORKDIR /tmp/adore
