ARG ADORE_CLI_TAG="latest"
ARG USER
ARG UID
ARG GID


FROM adore_cli_core_x11_display:${ADORE_CLI_TAG} as adore_cli

ARG USER
ARG UID
ARG GID

COPY /docker/files/own.sh /tmp/own.sh

USER root
WORKDIR /tmp
RUN bash own.sh ${USER} ${UID} ${GID}

USER ${USER}
